from .service_test_user import ServiceTestUserView
from .check_sheet import CheckSheetView
from .download_sheet import DownloadSheetFileAPIView
from .download_file import DownloadFileAPIView
from .generate_test import GenerateTestView
from .generate_test_for_def_keys import GenerateTestDefaultKey
from .languages import LanguagesView
from .subjects import SubjectsView
from .upload_document import UploadDocumentView
from .upload_file_with_image import UploadFileWithImageView
from .user_info import UserInfo
from .databaseType import DatabaseTypeView
from .downloadTitul import DownloadTitulView
from .titul_upload import TitulUploadAPIView
from .user_test_files_dwn import UserTestFilesView
from .user_checked_sheet_files_dwn import UserCheckedFilesView
from .bot_user import BotUserView
from .bot_user_info import BotUserInfo
from .bot_user_patch import BotUserPatchView
