# Generated by Django 4.2.1 on 2024-11-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='21.11.2024'),
            preserve_default=False,
        ),
    ]
