# Generated by Django 4.2.1 on 2025-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='checked_file',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='limit',
        ),
        migrations.AddField(
            model_name='botuser',
            name='balans',
            field=models.IntegerField(default=3000),
        ),
    ]
