# Generated by Django 4.2.1 on 2024-11-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='play_market',
        ),
    ]
