# Generated by Django 4.2.1 on 2025-01-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_botuser_checked_file_remove_botuser_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.botuser'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
