# Generated by Django 4.2.1 on 2025-01-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_fanlar_otm2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
