# Generated by Django 4.2.1 on 2025-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_botuser_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlokTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('ism_familiya', models.CharField(max_length=255)),
                ('telefon_raqam', models.CharField(max_length=255)),
                ('viloyat', models.CharField(max_length=255)),
                ('fan1', models.CharField(max_length=255)),
                ('fan2', models.CharField(max_length=255)),
                ('rejalashtirilgan_vaqt', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('kutmoqda', '🟡 Kutmoqda'), ('yechmoqda', '🟠 Yechmoqda'), ('yakunlandi', '🟢 Yakunlandi'), ('topshirmadi', '🔴 Topshirmadi')], default='kutmoqda', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Natijalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('ism', models.CharField(max_length=255)),
                ('viloyat', models.CharField(max_length=255)),
                ('blok1', models.CharField(max_length=255)),
                ('blok2', models.CharField(max_length=255)),
                ('majburiy_fanlar', models.IntegerField()),
                ('fan1', models.IntegerField()),
                ('fan2', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Natijalar',
                'verbose_name_plural': 'Natijalar',
            },
        ),
    ]
