# Generated by Django 4.2.1 on 2025-01-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_bloktest_natijalar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natijalar',
            name='ball',
            field=models.FloatField(),
        ),
    ]
