# Generated by Django 4.2.1 on 2025-01-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_natijalar_javoblari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natijalar',
            old_name='majburiy_fanlar',
            new_name='majburiy',
        ),
    ]
